sudo: required
dist: trusty
language: node_js
node_js:
  - '7'
cache:
  directories:
  - node_modules
install:
  - npm install -g truffle
  - npm install -g ganache-cli
  - npm install
script:
  - npm run test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
