sudo: required
language: node_js
node_js:
  - 'stable'
cache:
  directories:
  - node_modules
script:
  - ganache-cli -p 9545 -m 'candy maple cake sugar pudding cream honey rich smooth crumble sweet treat' > /dev/null &
  - sleep 5
  - truffle migrate
  - truffle test
